### PR TITLE
Update filterSearch to check if searchTerms is empty array

### LINKED ISSUE #11: Empty string should return whole collection
Hey, 

I updated from 0.23 to 0.24 and empty search param now returns nothing with an error:
`Error in render: "TypeError: t is null"`

I need to start typing something to see results.

It's maybe a regression, I could open a PR if needed unless with know how to fix it quickly.

Thanks in advance

### PR DESCRIPTION
**Pull request by guillaumebriday**
fix #11

### CODE REVIEW

**Comment by guillaumebriday** [comment]
ping @cuebit @kiaking :)

**Review by diegopamio — APPROVED** [review]
LGTM

**Comment by cuebit** [comment]
Sorry for the late intervention! LGTM 👍

**Review by cuebit — APPROVED** [review]

**Comment by guillaumebriday** [comment]
@cuebit No problem, could you please release it ? :)

**Comment by diegopamio** [comment]
Thanks! and BTW, great plugin!

**Comment by cuebit** [comment]
@guillaumebriday see [issue comment](https://github.com/vuex-orm/plugin-search/issues/11#issuecomment-685910471).

**Pull request merged**
